<?php if ($model_info->status === "new") { ?>
    <li role="presentation"><?php echo ajax_anchor(get_uri("estimate_requests/change_estimate_request_status/$model_info->id/processing"), "<i data-feather='refresh-cw' class='icon-16'></i> " . app_lang('mark_as_processing'), array("class" => "dropdown-item", "title" => app_lang('mark_as_processing'), "data-reload-on-success" => "1", "class" => "dropdown-item")); ?> </li>
    <li role="presentation"><?php echo ajax_anchor(get_uri("estimate_requests/change_estimate_request_status/$model_info->id/estimated"), "<i data-feather='check-circle' class='icon-16'></i> " . app_lang('mark_as_estimated'), array("class" => "dropdown-item", "title" => app_lang('mark_as_estimated'), "data-reload-on-success" => "1")); ?> </li>
    <li role="presentation"><?php echo ajax_anchor(get_uri("estimate_requests/change_estimate_request_status/$model_info->id/hold"), "<i data-feather='pause-circle' class='icon-16'></i> " . app_lang('mark_as_hold'), array("class" => "dropdown-item", "title" => app_lang('mark_as_hold'), "data-reload-on-success" => "1")); ?> </li>
    <li role="presentation"><?php echo ajax_anchor(get_uri("estimate_requests/change_estimate_request_status/$model_info->id/canceled"), "<i data-feather='x-circle' class='icon-16'></i> " . app_lang('mark_as_canceled'), array("class" => "dropdown-item", "title" => app_lang('mark_as_canceled'), "data-reload-on-success" => "1")); ?> </li>
<?php } else if ($model_info->status === "processing") { ?>
    <li role="presentation"><?php echo ajax_anchor(get_uri("estimate_requests/change_estimate_request_status/$model_info->id/estimated"), "<i data-feather='check-circle' class='icon-16'></i> " . app_lang('mark_as_estimated'), array("class" => "dropdown-item", "title" => app_lang('mark_as_estimated'), "data-reload-on-success" => "1")); ?> </li>
    <li role="presentation"><?php echo ajax_anchor(get_uri("estimate_requests/change_estimate_request_status/$model_info->id/hold"), "<i data-feather='pause-circle' class='icon-16'></i> " . app_lang('mark_as_hold'), array("class" => "dropdown-item", "title" => app_lang('mark_as_hold'), "data-reload-on-success" => "1")); ?> </li>
    <li role="presentation"><?php echo ajax_anchor(get_uri("estimate_requests/change_estimate_request_status/$model_info->id/canceled"), "<i data-feather='x-circle' class='icon-16'></i> " . app_lang('mark_as_canceled'), array("class" => "dropdown-item", "title" => app_lang('mark_as_canceled'), "data-reload-on-success" => "1")); ?> </li>
<?php } else if ($model_info->status === "estimated") { ?>
    <li role="presentation"><?php echo ajax_anchor(get_uri("estimate_requests/change_estimate_request_status/$model_info->id/processing"), "<i data-feather='check-circle' class='icon-16'></i> " . app_lang('mark_as_processing'), array("class" => "dropdown-item", "title" => app_lang('mark_as_processing'), "data-reload-on-success" => "1")); ?> </li>
    <li role="presentation"><?php echo ajax_anchor(get_uri("estimate_requests/change_estimate_request_status/$model_info->id/hold"), "<i data-feather='pause-circle' class='icon-16'></i> " . app_lang('mark_as_hold'), array("class" => "dropdown-item", "title" => app_lang('mark_as_hold'), "data-reload-on-success" => "1")); ?> </li>
    <li role="presentation"><?php echo ajax_anchor(get_uri("estimate_requests/change_estimate_request_status/$model_info->id/canceled"), "<i data-feather='x-circle' class='icon-16'></i> " . app_lang('mark_as_canceled'), array("class" => "dropdown-item", "title" => app_lang('mark_as_canceled'), "data-reload-on-success" => "1")); ?> </li>
<?php } else if ($model_info->status === "hold") { ?>
    <li role="presentation"><?php echo ajax_anchor(get_uri("estimate_requests/change_estimate_request_status/$model_info->id/processing"), "<i data-feather='check-circle' class='icon-16'></i> " . app_lang('mark_as_processing'), array("class" => "dropdown-item", "title" => app_lang('mark_as_processing'), "data-reload-on-success" => "1")); ?> </li>
    <li role="presentation"><?php echo ajax_anchor(get_uri("estimate_requests/change_estimate_request_status/$model_info->id/estimated"), "<i data-feather='pause-circle' class='icon-16'></i> " . app_lang('mark_as_estimated'), array("class" => "dropdown-item", "title" => app_lang('mark_as_estimated'), "data-reload-on-success" => "1")); ?> </li>
    <li role="presentation"><?php echo ajax_anchor(get_uri("estimate_requests/change_estimate_request_status/$model_info->id/canceled"), "<i data-feather='x-circle' class='icon-16'></i> " . app_lang('mark_as_canceled'), array("class" => "dropdown-item", "title" => app_lang('mark_as_canceled'), "data-reload-on-success" => "1")); ?> </li>
<?php } else if ($model_info->status === "canceled") { ?>
    <li role="presentation"><?php echo ajax_anchor(get_uri("estimate_requests/change_estimate_request_status/$model_info->id/processing"), "<i data-feather='check-circle' class='icon-16'></i> " . app_lang('mark_as_processing'), array("class" => "dropdown-item", "title" => app_lang('mark_as_processing'), "data-reload-on-success" => "1")); ?> </li>
    <li role="presentation"><?php echo ajax_anchor(get_uri("estimate_requests/change_estimate_request_status/$model_info->id/estimated"), "<i data-feather='pause-circle' class='icon-16'></i> " . app_lang('mark_as_estimated'), array("class" => "dropdown-item", "title" => app_lang('mark_as_estimated'), "data-reload-on-success" => "1")); ?> </li>
    <li role="presentation"><?php echo ajax_anchor(get_uri("estimate_requests/change_estimate_request_status/$model_info->id/hold"), "<i data-feather='pause-circle' class='icon-16'></i> " . app_lang('mark_as_hold'), array("class" => "dropdown-item", "title" => app_lang('mark_as_hold'), "data-reload-on-success" => "1")); ?> </li>
<?php } ?>